services:
  mysql1:
    image: mysql
    container_name: safeway_core
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=safeway
      - MYSQL_PASSWORD=urubu100
      - MYSQL_DATABASE=safeway_core
      - MYSQL_ROOT_PASSWORD=urubu100

  mysql2:
    image: mysql
    container_name: safeway_financial
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_USER=safeway
      - MYSQL_PASSWORD=urubu100
      - MYSQL_DATABASE=safeway_financial
      - MYSQL_ROOT_PASSWORD=urubu100
  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - redis-net
    volumes:
      - redisinsight_data:/data

networks:
  redis-net:
    driver: bridge

volumes:
  redis_data:
  redisinsight_data: